name: Golang CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  imports:
    name: Imports
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        # TODO Enable GO CI when the project has apps, examples and pkgs to check
        continue-on-error: true
        with:
          run: imports
          token: ${{ secrets.GITHUB_TOKEN }}

  errcheck:
    name: Errcheck
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        # TODO Enable GO CI when the project has apps, examples and pkgs to check
        continue-on-error: true
        with:
          run: errcheck
          token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        # TODO Enable GO CI when the project has apps, examples and pkgs to check
        continue-on-error: true
        with:
          run: lint
          token: ${{ secrets.GITHUB_TOKEN }}

  shadow:
    name: Shadow
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        # TODO Enable GO CI when the project has apps, examples and pkgs to check
        continue-on-error: true
        with:
          run: shadow
          token: ${{ secrets.GITHUB_TOKEN }}

  staticcheck:
    name: StaticCheck
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        # TODO Enable GO CI when the project has apps, examples and pkgs to check
        continue-on-error: true
        with:
          run: staticcheck
          token: ${{ secrets.GITHUB_TOKEN }}

  sec:
    name: Sec
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: check
        uses: grandcolline/golang-github-actions@v1.1.0
        # TODO Enable GO CI when the project has apps, examples and pkgs to check
        continue-on-error: true
        with:
          run: sec
          token: ${{ secrets.GITHUB_TOKEN }}
          flags: "-exclude=G104"
